# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:29:29+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class Address(BaseModel):
    city: Optional[str] = None
    country: Optional[str] = None
    countryCode: Optional[str] = None
    geonameID: Optional[int] = None
    ipaddress: Optional[str] = None
    nationality: Optional[str] = None
    phoneNumber: Optional[str] = None
    state: Optional[str] = None
    streetAddress: Optional[str] = None
    zipCode: Optional[str] = None


class Person(BaseModel):
    address: Optional[Address] = None
    age: Optional[int] = None
    bloodType: Optional[str] = None
    creditCardNumber: Optional[str] = None
    creditScore: Optional[int] = None
    dateOfBirth: Optional[str] = None
    email: Optional[str] = None
    eyeColor: Optional[str] = None
    gender: Optional[str] = None
    gpa: Optional[float] = None
    hasChildren: Optional[bool] = None
    hasDegree: Optional[bool] = None
    height: Optional[float] = None
    incomeInUSD: Optional[int] = None
    job: Optional[str] = None
    married: Optional[bool] = None
    name: Optional[str] = None
    politicalLeaning: Optional[float] = None
    religion: Optional[str] = None
    username: Optional[str] = None
    weight: Optional[float] = None


class ApiPersonNumberGetResponse(RootModel[List[str]]):
    root: List[str]


class Lifestory(BaseModel):
    lifestory: Optional[str] = None
    person: Optional[Person] = None
